export const APP_STRINGS = {
  APP_NAME: 'BFF',
  OOPS_ERROR: 'Oops! Something went wrong try again later',
  EMAIL_FIELD_EMPTY_ERROR:"Email cannot be empty",
  EMAIL_INVALID_ERROR:"Please enter a valid email address",
  PASSWORD_EMPTY_ERROR:"Password cannot be empty",
  PASSWORD_SHORT_ERROR:"Password is too short",
  OK:"Ok",
  OPEN_CAMERA: 'Open Camera',
  REMOVE_IMAGE: 'Remove Image',
  CANCEL: 'Cancel',
  UPLOAD_FROM_LIBRARY: 'Upload from Gallery',
  PERMISSIONS_ERROR: 'Permissions Denied',
  PERMISSIONS_ERROR_MESSAGE: 'Please enable permissions from settings',
  OPEN_SETTINGS: 'Open Settings',
};
